data_loader:
  train:
    gpu: 0
    args:
      batch_size: 1
      shuffle: true
      num_workers: 2
      pin_memory: false
      prefetch_factor: 2
      persistent_workers: false
  val:
    gpu: 0
    mp: false
    batch_freq: 1500
    args:
      batch_size: 2
      shuffle: false
      num_workers: 2
      pin_memory: true
      prefetch_factor: 2