eval_only: True
callbacks:

defaults:
  - validation@_group_.co: co
  - hydra: custom_hydra
  - data_loader_base
  - torch_environ_base
  - model: idedeqid
  - dataset: dsec_rec
  - _self_

model:
  name: RecIDE
  update_iters: 2
  pred_next_flow: true
  pretrain_ckpt: /home/elendil/GD/idnet/idn/checkpoint/tid.pt